INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (1, 'Validation Policy | Can create validation policy', 'validationpolicy', 'add_policy');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (2, 'Validation Policy | Can change validation policy', 'validationpolicy', 'change_policy');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (3, 'Validation Policy | Can delete validation policy', 'validationpolicy', 'delete_policy');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (8, 'Voter | Can delete voter', 'voter', 'delete_voter');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (10, 'Trustee | Can add trustee', 'trustee', 'add_trustee');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (12, 'Trustee | Can delete trustee', 'trustee', 'delete_trustee');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (13, 'Election Officer | Can add election officer', 'electionofficer', 'add_electionofficer');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (14, 'Election Officer| Can change election officer', 'electionofficer', 'change_electionofficer');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (15, 'Election Officer | Can delete election officer', 'electionofficer', 'delete_electionofficer');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (16, 'Election Role | Can add election role', 'electionrole', 'add_electionrole');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (17, 'Election Role | Can change election role', 'electionrole', 'change_electionrole');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (18, 'Election Role | Can delete election role', 'electionrole', 'delete_electionrole');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (27, 'Election | Can open election', 'election', 'open_election');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (28, 'Election | Can close election', 'election', 'close_election');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (6, 'Voters List | Can upload voters list', 'voterfile', 'upload_voterfile');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (22, 'Election | Can  define election ballot', 'election', 'define_ballot');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (29, 'Election | Can change election', 'election', 'change_election');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (30, 'Trustee | Can send trustee login information', 'trustee', 'can_send_trustee_url');
INSERT INTO helios_auth_permission (id, name, model_type, codename) VALUES (32, 'Election | Can release election results', 'election', 'can_release_election_results');